// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9V5oidf2ztSBlsXwzTsyZGPewzk4Q9cI',
    appId: '1:74427736097:web:f29c755a32e966a5e74360',
    messagingSenderId: '74427736097',
    projectId: 'litigation-app-5f964',
    authDomain: 'litigation-app-5f964.firebaseapp.com',
    storageBucket: 'litigation-app-5f964.firebasestorage.app',
    measurementId: 'G-QQWRY74S6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjt3mcit-WFS5iHHn4Yivii11MJJtivFg',
    appId: '1:74427736097:android:2aea3f2354b03affe74360',
    messagingSenderId: '74427736097',
    projectId: 'litigation-app-5f964',
    storageBucket: 'litigation-app-5f964.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD08rj80xTegIkOseuWrx3dBoIWy3EE-08',
    appId: '1:74427736097:ios:44335af4ef8efd50e74360',
    messagingSenderId: '74427736097',
    projectId: 'litigation-app-5f964',
    storageBucket: 'litigation-app-5f964.firebasestorage.app',
    iosBundleId: 'dev.tauqeer.litigationManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD08rj80xTegIkOseuWrx3dBoIWy3EE-08',
    appId: '1:74427736097:ios:44335af4ef8efd50e74360',
    messagingSenderId: '74427736097',
    projectId: 'litigation-app-5f964',
    storageBucket: 'litigation-app-5f964.firebasestorage.app',
    iosBundleId: 'dev.tauqeer.litigationManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9V5oidf2ztSBlsXwzTsyZGPewzk4Q9cI',
    appId: '1:74427736097:web:b6cda8b68681324be74360',
    messagingSenderId: '74427736097',
    projectId: 'litigation-app-5f964',
    authDomain: 'litigation-app-5f964.firebaseapp.com',
    storageBucket: 'litigation-app-5f964.firebasestorage.app',
    measurementId: 'G-7YR6RQDNZM',
  );
}
